### ISSUE TITLE
Extension Loading Issue

### ISSUE THREAD

**Issue by markjpT** [xinzhengzhang/bis#13]
Type: <b>Feature Request</b>

Problem Description:

Specific steps where the problem occurs: Open the browser and attempt to load the extension.
Actual result: The extension fails to load and an error message appears.
Expected result: The extension should load and run normally.

Extension version: 0.3.4
VS Code version: Code 1.83.0 (e7e037083ff4455cf320e344325dacb480062c3c, 2023-10-03T16:12:16.321Z)
OS version: Windows_NT x64 10.0.22631
Modes:

**Comment by xinzhengzhang** [comment]
Sorry, bis is not compatible with windows, most apple ecosystems can't run on windows, and I don't have a windows developer computer myself - -
What scenarios do you need to use in Windows? Such as swift or cc_binary?
