### ISSUE TITLE
引入 package.swift 会导致代码提示失效

### ISSUE THREAD

**Issue by TwoSX** [xinzhengzhang/bis#15]
前提：能正常在 vscode 中使用 bis 运行项目（SwiftUI）

由于项目需要引入其他第三方库，于是在 Bazel 中 引入 [rules_swift_package_manager](https://github.com/cgrindel/rules_swift_package_manager) 进行管理
按相关使用说明，在根目录中创建 Package.swift 文件，项目中可正常使用第三方库。

但是，vscode 的 swift 提示就失效了。经过排除，是 [swift插件](https://marketplace.visualstudio.com/items?itemName=sswg.swift-lang) 提示 `error: no tests found; create a target in the 'Tests' directory` 导致插件异常，不再继续工作了。

而 examples 中的代码能有提示，是因为插件检测到 `examples: Test Discovery Failed: error: Could not find Package.swift in this directory or any of its parent directories.` 所以跳过检索 Package.swift，能继续工作。

我尝试添加 Tests 目录，增加相关测试代码，也无法解决。我知道这不是 bis 的问题，想在这里请教下是否有其他思路可以解决。谢谢。

**Comment by xinzhengzhang** [comment]
bis使用的lsp是apple的lsp，他在workspace中第一步是检测是否是spm workspace https://github.com/apple/sourcekit-lsp/blob/8af0bb523b499c92657914f5c90b5515be680b5a/Sources/SourceKitLSP/Workspace.swift#L121 ，其次降级成了 CompilationDatabaseBuildSystem, 而bis的工作原理就是提供compile_commands 服务CompilationDatabaseBuildSystem。
这也是lsp检测到了spm的原因。建议方式是给spm套一层而不是在根目录workspace中。



> 前提：能正常在 vscode 中使用 bis 运行项目（SwiftUI）
> 
> 由于项目需要引入其他第三方库，于是在 Bazel 中 引入 [rules_swift_package_manager](https://github.com/cgrindel/rules_swift_package_manager) 进行管理 按相关使用说明，在根目录中创建 Package.swift 文件，项目中可正常使用第三方库。
> 
> 但是，vscode 的 swift 提示就失效了。经过排除，是 [swift插件](https://marketplace.visualstudio.com/items?itemName=sswg.swift-lang) 提示 `error: no tests found; create a target in the 'Tests' directory` 导致插件异常，不再继续工作了。
> 
> 而 examples 中的代码能有提示，是因为插件检测到 `examples: Test Discovery Failed: error: Could not find Package.swift in this directory or any of its parent directories.` 所以跳过检索 Package.swift，能继续工作。
> 
> 我尝试添加 Tests 目录，增加相关测试代码，也无法解决。我知道这不是 bis 的问题，想在这里请教下是否有其他思路可以解决。谢谢。

**Comment by TwoSX** [comment]
spm 套一层，并且重新调整 bazel 配置后。可以正常使用了。谢谢。

另外还有一个问题，vscode 的 `Restart` 调试功能无法正常使用。

提示 `Could not attach: no process found with process ID xxxxx`

你们这边有遇到过吗？

之前使用 [iOS Debug](https://marketplace.visualstudio.com/items?itemName=nisargjhaveri.ios-debug) 有一样的问题，不过它写明了不支持 `Restart`。

**Comment by xinzhengzhang** [comment]
> spm 套一层，并且重新调整 bazel 配置后。可以正常使用了。谢谢。
> 
> 另外还有一个问题，vscode 的 `Restart` 调试功能无法正常使用。
> 
> 提示 `Could not attach: no process found with process ID xxxxx`
> 
> 你们这边有遇到过吗？
> 
> 之前使用 [iOS Debug](https://marketplace.visualstudio.com/items?itemName=nisargjhaveri.ios-debug) 有一样的问题，不过它写明了不支持 `Restart`。

使用的是xcode中的device control的api，理论上他不支持也做不到，可以尝试使用手动杀进程重开后，attach的方式替代restart

**Comment by TwoSX** [comment]
尝试了还是不行。先不理它了。
